version: "3"
services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "renatogroff@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "airflow"
    ports:
      - "9999:80"
    depends_on:
      - postgres
  webserver:
      image: apache/airflow
      entrypoint: ./scripts/entrypoint.sh
#      restart_policy:
#          condition: on-failure
      depends_on:
          - postgres
      env_file:
          - .env_airflow
      volumes:
          - ./dags:/opt/airflow/dags
          - ./logs:/opt/airflow/logs
          - ./scripts:/opt/airflow/scripts
      ports:
          - "9998:8080"